name: ðŸ“¸ Image Builder

on:
  pull_request:
    branches:
    - main
  workflow_dispatch: {}

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    environment: 
      name: dockerhub
      url: https://hub.docker.com/r/kubed/krm
    steps:

    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Build Image
      uses: kubed-io/actions/build-image@main
      with: 
        push: false
        repository: kubed/krm