name: ðŸ§ Publish Version

on: 
  workflow_dispatch: 
    inputs: 
      action: 
        description: Version to bump to
        default: patch
        type: choice
        options:
        - patch
        - minor
        - major
        - premajor
        - preminor
        - prepatch
      push: 
        description: Push changes to the repository
        default: false
        type: boolean
jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest
    environment: 
      name: dockerhub
      url: ${{ steps.registry.outputs.url }}
    steps:

    - name: Create GitHub App Token
      uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}

    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ steps.app-token.outputs.token }}
    
    - name: Bump Version
      id: bump
      uses: duplocloud/version-bump@main
      with:
        token:  ${{ steps.app-token.outputs.token }}
        version: ${{ inputs.action }}
        push: ${{ inputs.push }}

    - name: Build Image
      uses: kubed-io/actions/build-image@main
      env:
        GIT_TAG: ${{ steps.bump.outputs.tag }}
      with: 
        push: ${{ inputs.push }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kubed/krm

    - name: Registry URL
      id: registry
      env:
        URL: https://hub.docker.com/r/kubed/krm
        VERSION: ${{ steps.bump.outputs.version }}
      run: |
        BADGE="[![Docker Hub](https://img.shields.io/docker/v/kubed/devcontainers)](${URL})"
        echo "url=${URL}" >> $GITHUB_OUTPUT
        echo "badge=${BADGE}" >> $GITHUB_OUTPUT

    - name: Create Release
      id: release
      if: inputs.push
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ steps.app-token.outputs.token }}
        name: ${{ steps.bump.outputs.tag }}
        tag_name: ${{ steps.bump.outputs.tag }}
        prerelease: false
        body: |
          [![Publish](${{ github.server_url }}/${{ github.repository }}/actions/workflows/publish.yml/badge.svg)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) ${{ steps.registry.outputs.badge }}

          ${{ steps.bump.outputs.release-notes }}

    - name: Summary 
      id: summary
      env:
        RELEASE_NOTES: ${{ steps.bump.outputs.release-notes }}
        NEW_VERSION: ${{ steps.bump.outputs.version }}
        PREVIOUS_VERSION: ${{ steps.bump.outputs.previous-version }}
        BADGE: ${{ steps.registry.outputs.badge }}
        URL: ${{ steps.release.outputs.url || '' }}
      run: |
        cat <<EOF > $GITHUB_STEP_SUMMARY
        ${BADGE} [![Release](https://img.shields.io/badge/Github-Release-blue?style=flat-square&logo=github)](${URL})
        New Version: ${NEW_VERSION}
        Previous Version: ${PREVIOUS_VERSION}

        ## Release Notes: 
        --------------
        ${RELEASE_NOTES}
        EOF